kind: ConfigMap
apiVersion: v1
metadata:
  name: teamvm-config
data:
    challenge_dir: {{.ChallengDir}}
    tmp_dir: {{.TempDir}} 
    init_file: {{.InitFile}}
    daemon_port: "{{.DaemonPort}}"
    ssh_password: "{{.SSHPassword}}"
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.TeamPodName}}
spec:
  selector:
    matchLabels:
      app: {{.TeamLabel}}
  template:
    metadata:
      labels:
        app: {{.TeamLabel}}
    spec:
      containers:
      - name: {{.ContainerName}}
        image: harbor.katana.local/katana/tsuka
        ports:
        - containerPort: 22
        env:
          - name: CHALLENGE_DIR 
            valueFrom:
              configMapKeyRef:
                name: teamvm-config          
                key: challenge_dir
          - name: TMP_DIR
            valueFrom:
              configMapKeyRef:
                name: teamvm-config
                key: tmp_dir
          - name: INIT_FILE
            valueFrom:
              configMapKeyRef:
                name: teamvm-config
                key: init_file
          - name: DAEMON_PORT
            valueFrom:
              configMapKeyRef:
                name: teamvm-config
                key: daemon_port
          - name: SSH_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: teamvm-config
                key: ssh_password
---
apiVersion: v1
kind: Service
metadata:
  name: tsuka-svc
spec:
  selector:
    app: {{.TeamLabel}}
  ports:
    - protocol: TCP
      port: 22
  type: ClusterIP