replicaCount: 1
image:
  repository: jfelten/openvpn-docker
  tag: 1.1.0
  pullPolicy: IfNotPresent
service:
  name: openvpn
  type: LoadBalancer
  externalPort: 443
  internalPort: 443
resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 128Mi
persistence:
  enabled: true

  existingClaim: openvpn-data-claim

  accessMode: ReadWriteOnce
  size: 1Gi
openvpn:
  OVPN_NETWORK: 10.240.0.0
  OVPN_SUBNET: 255.255.0.0
  OVPN_PROTO: tcp
  OVPN_K8S_POD_NETWORK: "10.244.0.0"
  OVPN_K8S_POD_SUBNET: "255.252.0.0"
